main
main.style.fill: lightgreen
main.style.stroke: firebrick
main.style.stroke-width: 3

main -> entry

entry
entry.style.fill: lightgreen
entry.style.stroke: firebrick
entry.style.stroke-width: 3

entry -> InitTask16
entry -> LockSegment16
entry -> GetVersion16
entry -> Int21GetDosVersInfo
entry -> WaitEvent16
entry -> InitApp16
entry -> pass1_1000_24db
entry -> interrupt_vector_op_1000_23ea
entry -> pass1_1000_262c
entry -> pass1_1000_27d6
entry -> ret_op_1000_55ac
entry -> init_1000_23be
entry -> fn_ptr_op_1000_24cd
entry -> pass1_1000_25a8
entry -> pass1_1000_2913
entry -> poss_str_op_1000_28dc
entry -> FatalAppExit16
entry -> FataExit

pass1_1000_24db
pass1_1000_24db.style.fill: lightgreen

pass1_1000_24db -> fn_ptr_op_1000_2594
pass1_1000_24db -> set_interrupt_vector_1000_256b
pass1_1000_24db -> DosInt21DuplicateFileHandle

interrupt_vector_op_1000_23ea
interrupt_vector_op_1000_23ea -> DosInt21GetInterruptVector
interrupt_vector_op_1000_23ea -> get_program_entry_point_1000_29dc
interrupt_vector_op_1000_23ea -> pass1_1000_25a8
interrupt_vector_op_1000_23ea -> pass1_1000_2913
interrupt_vector_op_1000_23ea -> poss_str_op_1000_28dc
interrupt_vector_op_1000_23ea.style.fill: lightgreen

pass1_1000_262c
pass1_1000_262c -> pass1_1000_2950
pass1_1000_262c -> GetModuleFileName16
pass1_1000_262c -> get_program_entry_point_1000_29dc
pass1_1000_262c.style.fill: lightgreen

pass1_1000_27d6
pass1_1000_27d6 -> GetDOSEnvironment16
pass1_1000_27d6 -> pass1_1000_2950
pass1_1000_27d6.style.fill: lightgreen

ret_op_1000_55ac
ret_op_1000_55ac.style.fill: lightgreen

init_1000_23be
init_1000_23be -> init_op_1008_54aa
init_1000_23be.style.fill: lightgreen
init_1000_23be.style.stroke: firebrick
init_1000_23be.style.stroke-width: 3

fn_ptr_op_1000_24cd
fn_ptr_op_1000_24cd -> fn_ptr_op_1000_2594
fn_ptr_op_1000_24cd -> ret_op_1000_55ac
fn_ptr_op_1000_24cd -> set_interrupt_vector_1000_256b
fn_ptr_op_1000_24cd -> DosInt21TerminateProcWithRetCode
fn_ptr_op_1000_24cd.style.fill: lightgreen

pass1_1000_25a8
pass1_1000_25a8 -> pass1_1000_2913
pass1_1000_25a8.style.fill: lightgreen

pass1_1000_2913
pass1_1000_2913 -> poss_str_op_1000_28dc
pass1_1000_2913 -> pass1_1000_55b1
pass1_1000_2913.style.fill: lightgreen

poss_str_op_1000_28dc
poss_str_op_1000_28dc.style.fill: lightgreen

fn_ptr_op_1000_2594
fn_ptr_op_1000_2594.style.fill: lightgreen

get_program_entry_point_1000_29dc
get_program_entry_point_1000_29dc.style.fill: lightgreen

pass1_1000_2950
pass1_1000_2950 -> mem_1000_167a
pass1_1000_2950 -> pass1_1000_25a8
pass1_1000_2950 -> pass1_1000_2913
pass1_1000_2950 -> FatalAppExit16
pass1_1000_2950 -> FatalExit
pass1_1000_2950.style.fill: lightgreen

init_op_1008_54aa
init_op_1008_54aa -> get_date_time_op_1000_435c
init_op_1008_54aa -> set_globals_1000_4d0c
init_op_1008_54aa -> pass1_1000_1fea
init_op_1008_54aa -> str_op_1008_60e8
init_op_1008_54aa -> mem_op_1000_179c
init_op_1008_54aa -> struct_op_1008_0000
init_op_1008_54aa -> main_win_msg_loop_1008_9498
init_op_1008_54aa -> mem_op_1000_1b68
init_op_1008_54aa.style.fill: lightgreen
init_op_1008_54aa.style.stroke: firebrick
init_op_1008_54aa.style.stroke-width: 3

set_interrupt_vector_1000_256b
set_interrupt_vector_1000_256b -> DosInt21SetInterruptVector
set_interrupt_vector_1000_256b.style.fill: lightgreen

pass1_1000_55b1
pass1_1000_55b1 -> pass1_1000_25a8
pass1_1000_55b1 -> pass1_1000_2913
pass1_1000_55b1 -> poss_str_op_1000_28dc
pass1_1000_55b1 -> FatalAppExit16
pass1_1000_55b1 -> FatalExit
pass1_1000_55b1.style.fill: lightgreen

FatalAppExit16
FatalAppExit16.style.fill: lightpink

FatalExit
FatalExit.style.fill: lightpink

mem_1000_167a
mem_1000_167a -> mem_op_1000_160a
mem_1000_167a -> mem_op_1000_0a48
mem_1000_167a.style.fill: lightgreen

get_date_time_op_1000_435c
get_date_time_op_1000_435c -> DosInt21GetDate
get_date_time_op_1000_435c -> DosInt21GetTime
get_date_time_op_1000_435c -> DosInt21GetDate
get_date_time_op_1000_435c -> pass1_1000_462e
get_date_time_op_1000_435c.style.fill: lightgreen

set_globals_1000_4d0c
set_globals_1000_4d0c.style.fill: lightgreen

pass1_1000_1fea
pass1_1000_1fea.style.fill: lightgreen

str_op_1008_60e8 {
    style : {
        fill: lightgreen
    }
}
str_op_1008_60e8 -> str_op_1000_3da4
str_op_1008_60e8 -> mem_op_1000_179c
str_op_1008_60e8 -> unk_str_op_1000_3d3e


str_op_1000_3da4 {
    style: {
        fill: lightgreen
    }
}

unk_str_op_1000_3d3e {
    style: {
        fill: lightgreen
    }
}

mem_op_1000_179c {
    style: {
        fill: lightgreen
    }
}
mem_op_1000_179c -> mem_op_1000_160a
mem_op_1000_179c -> fn_ptr_op_1000_1708

struct_op_1008_0000 {
    style: {
        fill: lightgreen
    }
}

main_win_msg_loop_1008_9498 {
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
main_win_msg_loop_1008_9498 -> GetMessage16
main_win_msg_loop_1008_9498 -> IsDialogMessage16
main_win_msg_loop_1008_9498 -> TranslateAccelerator16
main_win_msg_loop_1008_9498 -> DispatchMessage16


mem_op_1000_1b68

mem_op_1000_160a

mem_op_1000_0a48

pass1_1000_462e

fn_ptr_op_1000_1708

DosInt21GetDate
DosInt21GetDate.style.fill: lemonchiffon

DosInt21GetTime
DosInt21GetTime.style.fill: lemonchiffon

reg_class_1040_98c0 {
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
reg_class_1040_98c0 -> GetClassInfo16
reg_class_1040_98c0 -> RegisterClass16
reg_class_1040_98c0 -> fn_ptr_op_1000_24cd

set_struct_op_1008_0536 {
    style : {
        fill: lightgreen
    }
}
set_struct_op_1008_0536 -> pass1_1008_3ab8
set_struct_op_1008_0536 -> LoadIcon16
set_struct_op_1008_0536 -> LoadCursor16
set_struct_op_1008_0536 -> GetStockObject16
set_struct_op_1008_0536 -> mixed_1010_20ba
set_struct_op_1008_0536 -> unk_str_op_1000_3d3e
set_struct_op_1008_0536 -> set_sys_color_1008_357e

load_icon_1040_8b92 {
    style : {
        fill: lightgreen
    }
}
load_icon_1040_8b92 -> LoadIcon16

win_ui_op_1020_2cf0 {
    style : {
        fill: lightgreen
    }
}
win_ui_op_1020_2cf0 -> create_window_ex_1008_9760
win_ui_op_1020_2cf0 -> mixed_1010_20ba
win_ui_op_1020_2cf0 -> LoadIcon16
win_ui_op_1020_2cf0 -> mem_op_1000_179c
win_ui_op_1020_2cf0 -> load_draw_op_1020_2ede
win_ui_op_1020_2cf0 -> pass1_1018_0ac0
win_ui_op_1020_2cf0 -> pass1_1018_0b08
win_ui_op_1020_2cf0 -> MoveWindow16
win_ui_op_1020_2cf0 -> pass_1008_3e0e
win_ui_op_1020_2cf0 -> UpdateWindow16

window_op_1020_10a0 {
    style : {
        fill: lightgreen
    }
}
window_op_1020_10a0 -> create_window_ex_1008_9760
window_op_1020_10a0 -> mem_op_1000_179c
window_op_1020_10a0 -> pass1_1008_3bd6
window_op_1020_10a0 -> mixed_1010_20ba
window_op_1020_10a0 -> LoadIcon16
window_op_1020_10a0 -> unk_win_ui_op_1020_1418
window_op_1020_10a0 -> pass1_1018_04b8
window_op_1020_10a0 -> pass1_1010_41d6
window_op_1020_10a0 -> pass1_1010_451a
window_op_1020_10a0 -> pass1_1010_459e
window_op_1020_10a0 -> MoveWindow16
window_op_1020_10a0 -> UpdateWindow16

window_op_1020_6c3a{
    style : {
        fill: lightgreen
    }
}
window_op_1020_6c3a -> create_window_ex_1008_9760
window_op_1020_6c3a -> mixed_1010_20ba
window_op_1020_6c3a -> LoadIcon16
window_op_1020_6c3a -> pass1_1018_2d22
window_op_1020_6c3a -> mem_op_1000_179c
window_op_1020_6c3a -> pass1_1008_3bd6
window_op_1020_6c3a -> unk_win_ui_op_1020_717e
window_op_1020_6c3a -> MoveWindow16
window_op_1020_6c3a -> UpdateWindow16

unk_win_ui_op_1040_9854 {
    style : {
        fill: lightgreen
    }
}
unk_win_ui_op_1040_9854 -> unk_str_op_1000_3d3e
unk_win_ui_op_1040_9854 -> LoadCursor16
unk_win_ui_op_1040_9854 -> GetStockObject16
unk_win_ui_op_1040_9854 -> reg_class_1040_98c0
unk_win_ui_op_1040_9854 -> mixed_1010_20ba
unk_win_ui_op_1040_9854 -> win_ui_reg_class_1008_96d2

unk_draw_op_1020_41c8 {
    style : {
        fill: lightgreen
    }
}
unk_draw_op_1020_41c8 -> unk_draw_op_1020_7f7a
unk_draw_op_1020_41c8 -> LoadCursor16
unk_draw_op_1020_41c8 -> LoadAccelerators16
unk_draw_op_1020_41c8 -> mixed_1010_20ba

unk_draw_op_1008_80ee {
    style : {
        fill: lightgreen
    }
}
unk_draw_op_1008_80ee -> unk_str_op_1000_3d3e
unk_draw_op_1008_80ee -> LoadCursor16
unk_draw_op_1008_80ee -> GetStockObject16
unk_draw_op_1008_80ee -> pass1_1008_818c


unk_draw_op_1020_7f7a{
    style : {
        fill: lightgreen
    }
}
unk_draw_op_1020_7f7a -> unk_draw_op_1008_61b2
unk_draw_op_1020_7f7a -> unk_str_op_1000_3d3e
unk_draw_op_1020_7f7a -> GetStockObject16
unk_draw_op_1020_7f7a -> LoadCursor16
unk_draw_op_1020_7f7a -> mixed_1010_20ba
unk_draw_op_1020_7f7a -> win_ui_reg_class_1008_96d2



pass1_1008_818c

pass1_1008_3ab8

LoadIcon16

LoadCursor16

GetStockObject16

mixed_1010_20ba

set_sys_color_1008_357e

create_window_ex_1008_9760

load_draw_op_1020_2ede

pass1_1018_0ac0

pass1_1018_0b08

MoveWindow16

pass_1008_3e0e

UpdateWindow16

window_op_1008_3bd6

unk_win_ui_op_1020_1418

pass1_1018_04b8

pass1_1010_41d6

pass1_1010_451a

pass1_1010_459e

pass1_1018_2d22

unk_win_ui_op_1020_717e

win_ui_reg_class_1008_96d2

unk_draw_op_1008_61b2{
    style : {
        fill: lightgreen
    }
}
unk_draw_op_1008_61b2 -> set_struct_1008_687a
unk_draw_op_1008_61b2 -> unk_str_op_1000_3d3e
unk_draw_op_1008_61b2 -> GetStockObject16
unk_draw_op_1008_61b2 -> LoadCursor16
unk_draw_op_1008_61b2 -> mixed_1010_20ba
unk_draw_op_1008_61b2 -> win_ui_reg_class_1008_96d2

unk_draw_op_1008_7f62{
    style : {
        fill: lightgreen
    }
}
unk_draw_op_1008_7f62 -> set_struct_1008_687a
unk_draw_op_1008_7f62 -> unk_str_op_1000_3d3e
unk_draw_op_1008_7f62 -> GetStockObject16
unk_draw_op_1008_7f62 -> LoadCursor16
unk_draw_op_1008_7f62 -> win_ui_reg_class_1008_96d2

win_ui_op_1040_0170{
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
win_ui_op_1040_0170 -> enable_win_1040_060e
win_ui_op_1040_0170 -> GetDlgItem16
win_ui_op_1040_0170 -> EnableWindow16
win_ui_op_1040_0170 -> win_1008_5c5c
win_ui_op_1040_0170 -> pass1_1010_6604
win_ui_op_1040_0170 -> win_ui_op_1040_0558
win_ui_op_1040_0170 -> mixed_1010_20ba
win_ui_op_1040_0170 -> pass1_1030_8344
win_ui_op_1040_0170 -> pass1_1030_21fa
win_ui_op_1040_0170 -> set_window_text_1018_6086
win_ui_op_1040_0170 -> LoadCursor16
win_ui_op_1040_0170 -> SetCursor16
win_ui_op_1040_0170 -> pass1_1030_532e
win_ui_op_1040_0170 -> fn_ptr_1030_835a
win_ui_op_1040_0170 -> pass1_1030_838e
win_ui_op_1040_0170 -> pass1_1030_8334
win_ui_op_1040_0170 -> PostMessage16
win_ui_op_1040_0170 -> DestroyWindow16
win_ui_op_1040_0170 -> load_string_1010_847e
win_ui_op_1040_0170 -> SendDlgItemMessage16

window_op_1038_d8b2{
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
window_op_1038_d8b2 -> LoadCursor16
window_op_1038_d8b2 -> SetCursor16
window_op_1038_d8b2 -> dialog_ui_fn_1040_78e2
window_op_1038_d8b2 -> pass1_1010_0886
window_op_1038_d8b2 -> mem_op_1000_160a
window_op_1038_d8b2 -> fn_ptr_op_1000_1708
window_op_1038_d8b2 -> pass1_1010_08e2
window_op_1038_d8b2 -> MapDialogRect16
window_op_1038_d8b2 -> mem_op_1000_179c
window_op_1038_d8b2 -> pass1_1008_3db6
window_op_1038_d8b2 -> enable_win_1040_9234
window_op_1038_d8b2 -> mixed_1010_20ba
window_op_1038_d8b2 -> SetWindowText16
window_op_1038_d8b2 -> ShowWindow16
window_op_1038_d8b2 -> SetCursor16

win_ui_cursor_op_1038_bc30 {
    style : {
        fill: lightgreen
    }
}
win_ui_cursor_op_1038_bc30 -> LoadCursor16
win_ui_cursor_op_1038_bc30 -> SetCursor16
win_ui_cursor_op_1038_bc30 -> pass1_1030_532e
win_ui_cursor_op_1038_bc30 -> fn_ptr_1030_835a
win_ui_cursor_op_1038_bc30 -> pass1_1030_838e
win_ui_cursor_op_1038_bc30 -> pass1_1030_8334

unk_win_ui_op_1020_67ce{
    style : {
        fill: lightgreen
    }
}
unk_win_ui_op_1020_67ce -> struct_1020_790e
unk_win_ui_op_1020_67ce -> unk_str_op_1000_3d3e
unk_win_ui_op_1020_67ce -> GetStockObject16
unk_win_ui_op_1020_67ce -> LoadCursor16
unk_win_ui_op_1020_67ce -> win_ui_reg_class_1008_96d2
unk_win_ui_op_1020_67ce -> window_op_1020_6c3a

window_op_1020_5764{
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
window_op_1020_5764 -> mixed_1010_20ba
window_op_1020_5764 -> pass1_1030_8308
window_op_1020_5764 -> SetCursor16
window_op_1020_5764 -> ReleaseCapture16
window_op_1020_5764 -> LoadCursor16
window_op_1020_5764 -> pass1_1018_017c
window_op_1020_5764 -> pass1_1020_68de
window_op_1020_5764 -> PostMessage16
window_op_1020_5764 -> SetCursor16

win_ui_cursor_op_1020_1294{
    style : {
        fill: lightgreen
    }
}
win_ui_cursor_op_1020_1294 -> pass1_1010_40cc
win_ui_cursor_op_1020_1294 -> pass1_1008_3e94
win_ui_cursor_op_1020_1294 -> pt_in_rect_1010_40f8
win_ui_cursor_op_1020_1294 -> LoadCursor16
win_ui_cursor_op_1020_1294 -> SetCursor16
win_ui_cursor_op_1020_1294 -> pass1_1008_3e0e

cursor_op_1008_2dcc{
    style : {
        fill: lightgreen
    }
}
cursor_op_1008_2dcc -> LoadCursor16
cursor_op_1008_2dcc -> SetCursor16
cursor_op_1008_2dcc -> big_switch_1008_15d4
cursor_op_1008_2dcc -> ui_op_1008_24ce

win_ui_cursor_op_1008_2e9a{
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
win_ui_cursor_op_1008_2e9a -> mixed_1010_20ba
win_ui_cursor_op_1008_2e9a -> save_file_1008_3178
win_ui_cursor_op_1008_2e9a -> PostMessage16
win_ui_cursor_op_1008_2e9a -> unk_str_op_1000_3d3e
win_ui_cursor_op_1008_2e9a -> str_1000_4d58
win_ui_cursor_op_1008_2e9a -> pass1_1000_3cea
win_ui_cursor_op_1008_2e9a -> struct_1010_5f1e
win_ui_cursor_op_1008_2e9a -> send_msg_1020_097e
win_ui_cursor_op_1008_2e9a -> UpdateWindow16
win_ui_cursor_op_1008_2e9a -> LoadCursor16
win_ui_cursor_op_1008_2e9a -> SetCursor16
win_ui_cursor_op_1008_2e9a -> win_ui_op_1008_1414
win_ui_cursor_op_1008_2e9a -> str_op_1000_3da4

message_box_op_1008_12dc{
    style : {
        fill: lightgreen
    }
}
message_box_op_1008_12dc -> LoadCursor16
message_box_op_1008_12dc -> SetCursor16
message_box_op_1008_12dc -> str_1008_6d8a
message_box_op_1008_12dc -> file_fn_1008_6e02
message_box_op_1008_12dc -> load_string_1010_847e
message_box_op_1008_12dc -> str_op_1008_60e8
message_box_op_1008_12dc -> MessageBeep16
message_box_op_1008_12dc -> MessageBox16
message_box_op_1008_12dc -> fn_ptr_1000_17ce
message_box_op_1008_12dc -> close_file_1008_6dd0

win_ui_cursor_op_1008_06c0{
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
win_ui_cursor_op_1008_06c0 -> pass1_1030_8344
win_ui_cursor_op_1008_06c0 -> load_string_1010_847e
win_ui_cursor_op_1008_06c0 -> MessageBox16
win_ui_cursor_op_1008_06c0 -> LoadCursor16
win_ui_cursor_op_1008_06c0 -> SetCursor16
win_ui_cursor_op_1008_06c0 -> pass1_1030_83ba
win_ui_cursor_op_1008_06c0 -> mixed_1010_20ba
win_ui_cursor_op_1008_06c0 -> pass1_1018_262e
win_ui_cursor_op_1008_06c0 -> pass1_1030_8326
win_ui_cursor_op_1008_06c0 -> sys_1000_3f9c
win_ui_cursor_op_1008_06c0 -> pass1_1008_a9ec
win_ui_cursor_op_1008_06c0 -> PostMessage16

mixed_win_op_1008_0c60{
    style : {
        fill: lightgreen
        stroke: firebrick
        stroke-width: 3
    }
}
mixed_win_op_1008_0c60 -> pass1_1008_07d8
mixed_win_op_1008_0c60 -> win_ui_cursor_op_1008_2e9a
mixed_win_op_1008_0c60 -> pass1_1008_3018
mixed_win_op_1008_0c60 -> pass1_1008_30cc
mixed_win_op_1008_0c60 -> win_ui_op_1008_2b54
mixed_win_op_1008_0c60 -> pass1_1030_8344
mixed_win_op_1008_0c60 -> load_string_1010_847e
mixed_win_op_1008_0c60 -> MessageBox16
mixed_win_op_1008_0c60 -> LoadCursor16
mixed_win_op_1008_0c60 -> SetCursor16
mixed_win_op_1008_0c60 -> pass1_1018_262e
mixed_win_op_1008_0c60 -> pass1_1030_838e
mixed_win_op_1008_0c60 -> pass1_1030_8326
mixed_win_op_1008_0c60 -> sys_1000_3f9c
mixed_win_op_1008_0c60 -> mixed_1010_20ba
mixed_win_op_1008_0c60 -> pass1_1008_a9ec
mixed_win_op_1008_0c60 -> unk_io_op_1010_830a
mixed_win_op_1008_0c60 -> WinHelp16
mixed_win_op_1008_0c60 -> pass1_1038_af40
mixed_win_op_1008_0c60 -> WinExec16
mixed_win_op_1008_0c60 -> post_msg_1008_2d22
mixed_win_op_1008_0c60 -> pass1_1008_087e
mixed_win_op_1008_0c60 -> cursor_op_1008_2dcc
mixed_win_op_1008_0c60 -> win_1008_5c5c
mixed_win_op_1008_0c60 -> SendMessage16
mixed_win_op_1008_0c60 -> PostMessage16
mixed_win_op_1008_0c60 -> ui_op_1008_2c4e

pass1_1008_a9ec

sys_1000_3f9c

pass1_1030_8326

pass1_1018_262e

pass1_1030_83ba

load_string_1010_847e

file_fn_1008_6e02

str_1008_6d8a

win_ui_op_1008_1414

send_msg_1020_097e

struct_1010_5f1e

str_1000_4d58

pass1_1000_3cea

win_ui_cursor_op_1008_2e9a

win_ui_cursor_op_1008_2e9a

pass1_1010_40cc

pass1_1010_40cc

pass1_1010_40cc

pass1_1010_40cc

pass1_1020_68de

pass1_1018_017c

ReleaseCapture16

pass1_1030_8308

dialog_ui_fn_1040_78e2

pass1_1010_0886

pass1_1010_08e2

pass1_1008_3db6

enable_win_1040_9234

SetWindowText16

ShowWindow16

SetCursor16

GetDlgItem16

EnableWindow16

PostMessage16

DestroyWindow16

SendDlgItemMessage16

MapDialogRect16
