@startuml
[*] --> main #LightGreen

main --> entry #LightGreen

entry --> InitTask16 #yellow
entry --> LockSegment16 #yellow
entry --> GetVersion16 #yellow
entry --> Int21GetDosVersionInfo #yellow
entry --> WaitEvent16 #yellow
entry --> InitApp16 #yellow
entry --> pass1_1000_24db #LightGreen
entry --> interrupt_vector_op_1000_23ea #LightGreen
entry --> pass1_1000_27d6 #LightGreen
entry --> ret_op_1000_55ac #LightGreen
entry --> pass1_1000_25a8 #LightGreen
entry --> pass1_1000_2913 #LightGreen
entry --> poss_str_op_1000_28dc #LightGreen
entry --> FatalAppExit16 #yellow
entry --> FatalExit #yellow
entry --> init_1000_23be #LightGreen
entry --> pass1_1000_262c #LightGreen

pass1_1000_24db --> fn_ptr_op_1000_2594 #LightGreen
pass1_1000_24db --> set_interrupt_vector_1000_256b #LightGreen
pass1_1000_24db --> DosInt21DuplicateFileHandle #yellow

interrupt_vector_op_1000_23ea --> DosInt21GetInterruptVector #Yellow
interrupt_vector_op_1000_23ea --> get_program_entry_point_1000_29dc #LightGreen
interrupt_vector_op_1000_23ea --> pass1_1000_25a8 #LightGreen
interrupt_vector_op_1000_23ea --> pass1_1000_2913 #LightGreen
interrupt_vector_op_1000_23ea --> poss_str_op_1000_28dc #LightGreen
interrupt_vector_op_1000_23ea --> FatalAppExit16 #Yellow
interrupt_vector_op_1000_23ea --> FatalExit #Yellow
interrupt_vector_op_1000_23ea --> fn_ptr_op_1000_2594 #LightGreen

pass1_1000_27d6 --> GetDosEnvironment16 #Yellow
pass1_1000_27d6 --> pass1_1000_2950 #LightGreen

pass1_1000_25a8 --> pass1_1000_2913 #LightGreen

pass1_1000_2913 --> poss_str_op_1000_28dc
pass1_1000_2913 --> pass1_1000_55b1

init_1000_23be --> init_op_1008_54aa

pass1_1000_262c --> GetModuleFileName16 #Yellow
pass1_1000_262c --> pass1_1000_29dc

set_interrupt_vector_1000_256b --> DosInt21SetInterruptVector #Yellow

poss_str_op_1000_28dc #LighGreen

pass1_1000_2950 --> mem_1000_167a
pass1_1000_2950 --> pass1_1000_25a8
pass1_1000_2950 --> pass1_1000_2913
pass1_1000_2950 --> poss_str_op_1000_28dc
pass1_1000_2950 --> FatalAppExit16
pass1_1000_2950 --> FatalExit


@enduml