@ stdcall main_test
@ stdcall test_retval
@ stdcall da_immediate
@ stdcall da_deferred
@ stdcall nested
@ stdcall cf_present
@ stdcall cf_absent
@ stdcall crs_present
@ stdcall crs_absent
@ stdcall env_present
@ stdcall env_absent
@ stdcall file_present
@ stdcall file_absent
@ stdcall font_present
@ stdcall font_absent
@ stdcall ini_present
@ stdcall ini_absent
@ stdcall mov_present
@ stdcall mov_absent
@ stdcall odbc_present
@ stdcall odbc_absent
@ stdcall pa_present
@ stdcall pa_absent
@ stdcall pf_present
@ stdcall pf_absent
@ stdcall pp_present
@ stdcall pp_absent
@ stdcall ppc_present
@ stdcall ppc_absent
@ stdcall pub_present
@ stdcall pub_absent
@ stdcall rci_present
@ stdcall rci_absent
@ stdcall rei_present
@ stdcall rei_absent
@ stdcall rmi_present
@ stdcall rmi_absent
@ stdcall rd_present
@ stdcall rd_absent
@ stdcall rp_present
@ stdcall rp_absent
@ stdcall rpi_present
@ stdcall rpi_absent
@ stdcall ru_present
@ stdcall ru_absent
@ stdcall sds_present
@ stdcall sds_absent
@ stdcall sis_present
@ stdcall sis_absent
@ stdcall sr_present
@ stdcall sr_absent
@ stdcall sss_started
@ stdcall sss_stopped
@ stdcall tl_present
@ stdcall tl_absent
@ stdcall wrv_present
@ stdcall wrv_absent
