[package]
name = "outpost_rs_proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1"

[[bin]]
name = "outpost_rs_proj"
path = "src/main.rs"
